jaeger.tracer:
  host: localhost
  port: 6831
spring:
  application:
    name: test-app
kafka:
  request-topic: request
  response-topic: response
  producer-id: ${spring.application.name}
  consumer-group-id: ${spring.application.name}
  bootstrap-servers: localhost:32770

opentracing:
  jaeger:
    service-name: ${spring.application.name}
    enable-b3-propagation: true
    udp-sender:
      host: localhost

send-delay: 5000
server:
  port: 8080