apiVersion: v1
kind: Service
metadata:
  name: kafka-app
  namespace: kafka-cluster
  labels:
    name: kafka-app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: kafka-app